[PHP]
engine = On
short_open_tag = Off
precision = 14
output_buffering = 4096
zlib.output_compression = Off
implicit_flush = Off
serialize_precision = -1
zend.enable_gc = On
expose_php = Off
max_execution_time = 120
max_input_time = 120
memory_limit = 512M
error_reporting = E_ALL
display_errors = On
display_startup_errors = Off
log_errors = On
variables_order = "GPCS"
request_order = "GP"
post_max_size = 64M
upload_max_filesize = 64M
default_mimetype = "text/html"
default_charset = "UTF-8"
file_uploads = On
allow_url_fopen = On
extension_dir = "C:\projects\sunglass\.tools\php83\ext"
extension=curl
extension=fileinfo
extension=intl
extension=mbstring
extension=openssl
extension=pdo_pgsql
extension=pdo_sqlite
extension=pgsql
extension=sqlite3
extension=zip
[Date]
date.timezone = Asia/Dhaka
